CREATE DATABASE ACTIVIDAD

USE ACTIVIDAD

--HADER ELDIR MAYA MUÑOZ

--FICHA : 2340534

--CREAR TABLAS
CREATE TABLE DETALLE_CONTRATO
(
COD_EDIF CHAR (6) NOT NULL,
COD_DEP CHAR (6) NOT NULL,
COD_CONT CHAR(6) NOT NULL,
FEC_INI_ALQ DATE NOT NULL,
FEC_FIN_ALQ DATE NOT NULL
)

CREATE TABLE DEPARTAMENTOS
(
COD_EDIF CHAR(6) NOT NULL,
COD_DEP CHAR (6) NOT NULL,
AREA_TOTAL_DEP VARCHAR(50)NOT NULL,
AREA_CONSTRUIDA_DEP VARCHAR(50) NOT NULL,
NUM_AMB_DEP VARCHAR(50) NOT NULL,
PISO_DEP VARCHAR(50) NOT NULL,
PRECIO_ALQXMES_DEP VARCHAR(50) NOT NULL,
COD_EST CHAR (6) NOT NULL,
)

CREATE TABLE EDIFICIOS
(
COD_EDIF CHAR(6) NOT NULL,
NOM_EDIF VARCHAR(50) NOT NULL,
DIRECC_EDIF VARCHAR(50) NOT NULL,
COOPOSTAL VARCHAR(50) NOT NULL,
AREA_TOTAL_EDIF VARCHAR(50) NOT NULL,
AREA_CONSTRUIDA_EDI VARCHAR(50) NOT NULL,
REFERENCIAS_EDIF VARCHAR(50) NOT NULL,
COD_EST CHAR(6) NOT NULL,
)

CREATE TABLE CONTRATO
(
 COD_CONT CHAR (6) NOT NULL,
 COD_USUA CHAR (6) NOT NULL,
 PROP_COD_USUA VARCHAR(50) NOT NULL,
 INQ_COD_USUA VARCHAR(50) NOT NULL,
 FEC_FIRMA VARCHAR(50) NOT NULL,
 REFERENCIA VARCHAR(50) NOT NULL,
 COD_EST CHAR(6) NOT NULL,
 COD_CONT_ORIG VARCHAR(50) NOT NULL,
)


CREATE TABLE ESTADO
(
COD_EST CHAR(6) NOT NULL,
DESC_EST VARCHAR(50) NOT NULL,
)

CREATE TABLE USUARIOS
(
 COD_USUA CHAR(6) NOT NULL,
 NOM_USUA VARCHAR (50) NOT NULL,
 APEPATER_USUA VARCHAR(50) NOT NULL,
 APEMATER_USUA VARCHAR(50) NOT NULL,
 FEC_NAC_USUA VARCHAR(50) NOT NULL,
 FEC_REG_USUA VARCHAR(50) NOT NULL,
 TIPO_DOC_USUA VARCHAR(50) NOT NULL,
 NUM_DOC_USUA VARCHAR(50) NOT NULL,
 COD_EST CHAR(6) NOT NULL,
)

CREATE TABLE INQUILINOS
(
  COD_USUA CHAR(6) NOT NULL,
  NOM_AVAL_INQ VARCHAR(50) NOT NULL,
  APELL_AVAL VARCHAR(50) NOT NULL,
  HABER_BAS_INQ VARCHAR(50) NOT NULL,
  EST_CIVIL_INQ VARCHAR(50) NOT NULL,
  LUG_TRAB_INQ VARCHAR(50) NOT NULL,
)

CREATE TABLE FAMILIARESS
(
 COD_FAMI CHAR(6) NOT NULL,
 COD_USUA CHAR(6) NOT NULL,
 NOM_FAMI VARCHAR(50) NOT NULL,
 APEPATER_FAMI VARCHAR(50) NOT NULL,
 APEMATER_FAMI VARCHAR(50) NOT NULL,
 GRADO_PARENTES_FAMI VARCHAR(50) NOT NULL,
)

CREATE TABLE PROPIETARIOS
(
 COD_USUA CHAR(6) NOT NULL,
 TIPO VARCHAR(50) NOT NULL,
)

-- CLAVES PRIMARIAS

ALTER TABLE DEPARTAMENTOS
ADD CONSTRAINT PK_DEPARTAMENTOS PRIMARY KEY (COD_DEP)

ALTER TABLE EDIFICIOS
ADD CONSTRAINT PK_EDIFICIOS PRIMARY KEY (COD_EDIF)

ALTER TABLE CONTRATO
ADD CONSTRAINT PK_CONTRATO PRIMARY KEY (COD_CONT)

ALTER TABLE ESTADO
ADD CONSTRAINT PK_ESTADO PRIMARY KEY (COD_EST)

ALTER TABLE USUARIOS
ADD CONSTRAINT PK_USUARIOS PRIMARY KEY (COD_USUA)

ALTER TABLE INQUILINOS
ADD CONSTRAINT PK_INQUILINOS PRIMARY KEY (COD_USUA)

ALTER TABLE FAMILIARESS
ADD CONSTRAINT PK_FAMILIARESS PRIMARY KEY (COD_FAMI)

ALTER TABLE PROPIETARIOS
ADD CONSTRAINT PK_PROPIETARIOS PRIMARY KEY (COD_USUA)

-- CLAVE COMPUESTA
ALTER TABLE DETALLE_CONTRATO
ADD CONSTRAINT PK_DETALLE_CONTRATO PRIMARY KEY (COD_EDIF,COD_DEP,COD_CONT)

-- LLAVES FORANEAS 
ALTER TABLE DEPARTAMENTOS
ADD CONSTRAINT FK_DEPARTAMENTOS_ FOREIGN KEY (COD_EDIF)
REFERENCES EDIFICIOS(COD_EDIF)

ALTER TABLE DETALLE_CONTRATO
ADD CONSTRAINT FK_DETALLE_CONTRATO_CONTRATO FOREIGN KEY (COD_CONT)
REFERENCES CONTRATO(COD_CONT)

ALTER TABLE DETALLE_CONTRATO
ADD CONSTRAINT FK_DETALLE_CONTRATO_DEPARTAMENTOS FOREIGN KEY (COD_DEP)
REFERENCES DEPARTAMENTOS(COD_DEP)



ALTER TABLE CONTRATO
ADD CONSTRAINT FK_CONTRATO FOREIGN KEY (COD_EST)
REFERENCES ESTADO(COD_EST)

ALTER TABLE DEPARTAMENTOS
ADD CONSTRAINT FK_DEPARTAMENTOS_1 FOREIGN KEY (COD_EST)
REFERENCES ESTADO(COD_EST)

ALTER TABLE EDIFICIOS
ADD CONSTRAINT FK_EDIFICIOS FOREIGN KEY (COD_EST)
REFERENCES ESTADO(COD_EST)

ALTER TABLE USUARIOS
ADD CONSTRAINT FK_USUARIOS FOREIGN KEY (COD_EST)
REFERENCES ESTADO(COD_EST)

ALTER TABLE CONTRATO
ADD CONSTRAINT FK_CONTRATO_C FOREIGN KEY (COD_USUA)
REFERENCES INQUILINOS(COD_USUA)

ALTER TABLE INQUILINOS
ADD CONSTRAINT FK_INQUILINOS FOREIGN KEY (COD_USUA)
REFERENCES USUARIOS(COD_USUA)

ALTER TABLE FAMILIARESS
ADD CONSTRAINT FK_FAMILIARESS FOREIGN KEY (COD_USUA)
REFERENCES INQUILINOS(COD_USUA)

ALTER TABLE CONTRATO
ADD CONSTRAINT FK_CONTRATO_ FOREIGN KEY (COD_USUA)
REFERENCES PROPIETARIOs(COD_USUA)

ALTER TABLE PROPIETARIOS
ADD CONSTRAINT FK_PROPIETARIOS FOREIGN KEY (COD_USUA)
REFERENCES USUARIOS(COD_USUA)

ALTER TABLE CONTRATO
ADD CONSTRAINT FK_CONTRATO_1 FOREIGN KEY (COD_CONT)
REFERENCES CONTRATO(COD_CONT)